Controllers/AuthController.cs
using EmptyTest.Exceptions;
using EmptyTest.Helpers;
using EmptyTest.Models.Requests.Auth;
using EmptyTest.Models.Requests.Queries;
using EmptyTest.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;

namespace EmptyTest.Controllers;
public class AuthController : Controller
{
    private readonly IAuthService _authService;

    public AuthController(IAuthService authService)
    {
        _authService = authService;
    }

    public IActionResult SignIn([FromQuery] SingInQuery query)
    {
        ViewData["RedirectUrl"] = query.RedirectUrl;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> SignIn(SignInRequest requestModel, [FromQuery] SingInQuery query)
    {
        if (!ModelState.IsValid) return View();

        var principal = await _authService.SignIn(requestModel);
        if (principal is null)
        {
            ViewData["SignInError"] = "Invalid email or password";
        }
        else
        {
            await HttpContext.SignInAsync(AuthenticationSchemas.Default, principal, new AuthenticationProperties
            {
                IsPersistent = true
            });
            return Redirect(query.RedirectUrl ?? Routes.HomePage);
        }
        return View();
    }

    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register(RegisterAccountRequest requestModel)
    {
        if (!ModelState.IsValid) return View();

        try
        {
            await _authService.RegisterAccount(requestModel);
            ViewData["RegisterSuccess"] = "Successfully created an account";
        }
        catch (BadRequestException ex)
        {
            ViewData["RegisterError"] = ex.Message;
        }

        return View();
    }

    public IActionResult AccountSettings()
    {
        return View();
    }

    public IActionResult Logout()
    {
        HttpContext.SignOutAsync();
        return Redirect(Routes.HomePage);
    }
}

Controllers/TutorialsController.cs
using EmptyTest.Helpers;
using EmptyTest.Models.Requests.MyTutorials;
using EmptyTest.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EmptyTest.Controllers;

[Authorize]
[Route("[controller]")]
[Controller]
public class TutorialsController : Controller
{
    private readonly ITutorialService _tutorialService;
    private readonly IUserContextService _userContextService;

    public TutorialsController(ITutorialService tutorialService, IUserContextService userContextService)
    {
        _tutorialService = tutorialService;
        _userContextService = userContextService;
    }

    [Route("{id}")]
    [AllowAnonymous]
    public async Task<IActionResult> GetTutorialById([FromRoute] Guid id)
    {
        var tutorial = await _tutorialService.GetTutorialById(id);
        if (tutorial is null)
        {
            return Redirect(Routes.HomePage);
        }

        ViewData["IsAuthor"] = false;

        var accountIdClaim = _userContextService.AccountId;
        Guid.TryParse(accountIdClaim?.Value, out Guid accountId);
        if (accountId == tutorial?.AccountId)
        {
            ViewData["IsAuthor"] = true;
        }

        return View("TutorialById", tutorial);
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var tutorials = await _tutorialService.GetAccountTutorialsAsync();
        return View("Index", tutorials);
    }

    [Route("[action]")]
    public IActionResult CreateTutorial()
    {
        return View();
    }

    [HttpPost]
    [Route("CreateTutorial")]
    public async Task<IActionResult> CreateTutorial([FromForm] CreateTutorialRequest requestModel)
    {
        if (!ModelState.IsValid) return View(requestModel);

        var result = await _tutorialService.CreateTutorialAsync(requestModel);
        switch (result)
        {
            case ServiceResult.UnAuthorized:
                return Redirect(Routes.SignInPage);
            case ServiceResult.ValidationError:
                ViewData["NameError"] = "You've already created tutorial at this name";
                return View();
        }

        return View();
    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewData["Title"] | @ViewData["AppName"]</title>
        @await RenderSectionAsync("TutorialByIdScript", false)
        <partial name="Partials/_ScriptsPartial" />
        <partial name="Partials/_LinksPartial" />
    </head>
    <body>
        <nav class="navbar navbar-expand-md bg-light navbar-light border-bottom navigation">
            <div class="container-fluid">
                <a href="/" class="navbar-brand">@ViewData["AppName"]</a>
                
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#main-menu" aria-controls="main-menu" aria-expanded="false">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div id="main-menu" class="collapse navbar-collapse">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item"><a href="/" class="nav-link">Home</a></li>
                        @if(User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item"><a asp-controller="Tutorials" asp-action="Index" class="nav-link">My Tutorials</a></li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if(User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item"><a class="nav-link" asp-controller="Auth" asp-action="LogOut">Logout</a></li>
                            <li class="nav-item">
                                <a class="nav-link border-bottom" asp-controller="Auth" asp-action="AccountSettings">@User.FindFirstValue(ClaimTypes.Email)</a>
                            </li>
                        }
                        else 
                        {
                            <li class="nav-item"><a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Auth" asp-action="SignIn">Sing In</a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container main-container">
            @RenderBody()
        </div>
    </body>
</html>